### PR TITLE
rename regex to re, 

### PR DESCRIPTION
**Pull request by DGrothe-PhD**
First of all, thank you for the very useful application! 

1) As I didn't have `regex` package installed, I noticed that standard `re` works well. So there is no need to additionally install [regex](https://pypi.org/project/regex/) I guess.

2) My situation is I have a German Windows environment and most of the PDFs are in German as well.
**See below:** I noticed that (at least on mine) the voices don't have a "gender" property, and there doesn't seem to be a male voice anyway in my list.
So I added an option "s" (for "system") to reflect this.

## pyttsx3 voices description on my machine
```
<Voice id=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_DE-DE_HEDDA_11.0
          name=Microsoft Hedda Desktop - German
          languages=[]
          gender=None
          age=None>
<Voice id=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-GB_HAZEL_11.0
          name=Microsoft Hazel Desktop - English (Great Britain)
          languages=[]
          gender=None
          age=None>
<Voice id=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_EN-US_ZIRA_11.0
          name=Microsoft Zira Desktop - English (United States)
          languages=[]
          gender=None
          age=None>
<Voice id=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens\TTS_MS_FR-FR_HORTENSE_11.0
          name=Microsoft Hortense Desktop - French
          languages=[]
          gender=None
          age=None>
```

### CODE REVIEW

**Comment by partigabor** [comment]
Hi! Thanks for your contribution. Your addition is useful, since everyone has a different machine and `pytts3` seems to choose one from your system's [synthesizers](https://pyttsx3.readthedocs.io/en/latest/support.html). Good to know it can work in German now. I also had no idea that `re` is a standard library in python but `regex` is not, I guess for purposes in this project `re` is enough. I will test and merge soon.

By the way, I am quite surprised that anyone have actually found this silly attempt, as I am sure there are much better solutions out there. I hope it was useful to you in some way.

**Comment by DGrothe-PhD** [comment]
There might be (including smartphones for example..), but it is not silly to gather raw text for reading without connection to Google. So maybe I can use it to turn an old laptop with a scanner connected to a letter-reading machine for someone who can't read anything. 
After all, Adobe Reader's built-in reader solution is not suitable at all, for example it just reads one word of an invoice at once if you click in the right text line.

**Comment by DGrothe-PhD** [comment]
Closing this as obsolete, all changes hereof have been already merged with the other PR. Thanks!

**Comment by partigabor** [comment]
Thank you for the great quality work, I think your contribution is very useful. Now you I am thinking to put some more days of work into this and make it decent and useful later when I have a bit of time.

**Pull request closed without merging**
